spring:
  application:
    name: springbootWithJsp
  threads:
    virtual:
      enabled: true
  mvc:
    view:
      prefix: /
      #prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  servlet:
    context-path: /

db:
  pass: ทดสอบภาษาไทย
  user: kkk
  
