spring.application.name=springbootWithJsp

spring.threads.virtual.enabled=true
#server.servlet.context-path=/myapp

#spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp